name: Test oidc token

on:
    workflow_dispatch

permissions:
  id-token: write

jobs:
    do-test-token:
        runs-on: ubuntu-latest
        name: Test team token from oidc
        steps:
            - name: Pulumi Auth
              uses: pulumi/auth-actions@v1
              with:
                organization: pequod
                requested-token-type: urn:pulumi:token-type:access_token:team
                scope: team:env-admin-pk
                cloud-url: https://api.eu.pulumi.com
            - name: Install Pulumi
              uses: pulumi/actions@v6
              with: 
                pulumi-version: "v3.215.0"
            - name: Run pulumi about
              run: pulumi about
            - name: Run pulumi whoai
              run: pulumi whoami -v
            - name: Pulumi ESC ls
              run: pulumi env ls